create table Department
(
    id   int primary key generated by default as identity,
    name varchar(50) not null
);
create table Employee
(
    id            int primary key generated by default as identity,
    first_name    varchar(50)              not null,
    last_name     varchar(50)              not null unique,
    position      varchar(100)             not null,
    salary        int check ( salary > 0 ) not null,
    department_id int references Department (id) on delete cascade
);

insert into Department(name)
VALUES ('Department1');
insert into Department(name)
VALUES ('Department2');
insert into Department(name)
VALUES ('Department3');
insert into Department(name)
VALUES ('Department4');

insert into Employee(first_name, last_name, position, salary, department_id)
VALUES ('Margo', 'Robin', 'Actor', 1000, 1);
insert into Employee(first_name, last_name, position, salary, department_id)
VALUES ('Scrooge', 'McDuck', 'Manager', 10000, 2);
insert into Employee(first_name, last_name, position, salary, department_id)
VALUES ('John', 'Collins', 'Cleaner', 4000, 3);
insert into Employee(first_name, last_name, position, salary, department_id)
VALUES ('Sofia', 'Anderson', 'Redactor', 7000, 4);